Merged PR 18895: bug: Fix the buildx issue
# 🔍 Description

This PR fixes a prior failure in the trident-PullRequest pipeline. Before, the following error was seen:

/bin/bash --noprofile --norc /mnt/vss/_work/1/b/2/_work/_temp/1f8a4f6b-50ca-4086-9b35-867a02e11b1d.sh
mkdir -p ./artifacts/systemd
curl https://hermesimages.blob.core.windows.net/hermes-test/systemd-254-3.tar.gz | tar -xz -C ./artifacts/systemd --strip-components=1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  9 58.3M    9 5888k    0     0  4643k      0  0:00:12  0:00:01  0:00:11 4643k
 51 58.3M   51 29.7M    0     0  12.8M      0  0:00:04  0:00:02  0:00:02 12.8M
 96 58.3M   96 56.0M    0     0  17.1M      0  0:00:03  0:00:03 --:--:-- 17.1M
100 58.3M  100 58.3M    0     0  17.5M      0  0:00:03  0:00:03 --:--:-- 17.5M
rm -f ./artifacts/systemd/*.src.rpm ./artifacts/systemd/systemd-debuginfo*.rpm ./artifacts/systemd/systemd-devel-*.rpm
ERROR: BuildKit is enabled but the buildx component is missing or broken.
       Install the buildx component to build images with BuildKit:
       https://docs.docker.com/go/buildx/

##[error]Bash exited with code '1'.
##[warning]RetryHelper encountered task failure, will retry (attempt #: 1 out of 3) after 1000 ms

Related work items: #7657

diff --git a/.pipelines/templates/stages/trident_rpms/release.yml b/.pipelines/templates/stages/trident_rpms/release.yml
--- a/.pipelines/templates/stages/trident_rpms/release.yml
+++ b/.pipelines/templates/stages/trident_rpms/release.yml
@@ -49,13 +49,44 @@ steps:
   - template: common/setup-registries-template.yaml@platform-pipelines
 
   - script: |
-      set -eu
+      set -eux
 
       # Download newer systemd RPMs (needed until we switch to AZL3)
       make artifacts/systemd/systemd-254-3.cm2.x86_64.rpm
 
       mkdir -p bin
       cp -r /usr/src/mariner/RPMS bin/
+
+      # Explicitly check for Docker Buildx and install if not available
+      if [ ! -f ~/.docker/cli-plugins/docker-buildx ]; then
+          echo "Docker Buildx not found. Installing..."
+
+          # Determine system architecture for downloading the correct Buildx binary
+          ARCH=$(uname -m)
+          case "$ARCH" in
+              x86_64) ARCH="amd64";;
+              aarch64) ARCH="arm64";;
+              arm*) ARCH="arm-v7";;
+              *) echo "Unsupported architecture: $ARCH"; exit 1;;
+          esac
+
+          # Set the desired version of Buildx
+          BUILDX_VERSION="v0.8.2"
+
+          # Compose Buildx binary path
+          BUILDX_BIN_PATH="https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-${ARCH}"
+
+          # Download and install Buildx
+          mkdir -p ~/.docker/cli-plugins
+          curl -sSL $BUILDX_BIN_PATH -o ~/.docker/cli-plugins/docker-buildx
+          chmod a+x ~/.docker/cli-plugins/docker-buildx
+          echo "Docker Buildx installed."
+          echo "Docker Buildx version:"
+          ~/.docker/cli-plugins/docker-buildx version
+      else
+          echo "Docker Buildx is already installed."
+      fi
+
       DOCKER_BUILDKIT=1 docker build -f Dockerfile.runtime --progress plain -t trident/trident:latest .
 
       # ado redacts random strings (like `ecfafoncpriv`). To still be able
