try adding serial collection during update

diff --git a/.pipelines/templates/stages/testing_common/e2e-test-run.yml b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
--- a/.pipelines/templates/stages/testing_common/e2e-test-run.yml
+++ b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
@@ -51,6 +51,9 @@ parameters:
   - name: netlistenPort
     type: number
     default: 4000
+  
+  - name: tridentConfigFile
+    type: string
 
 steps:
   - bash: |
@@ -113,6 +116,8 @@ steps:
         --full-logstream ./logstream-full.log \
         -s "${{ parameters.artifactsDirectory }}" \
         -p ${{ parameters.netlistenPort }} > ./stage-finalize-ab-update-runtime-os-B.log 2>&1 &
+      
+      ./bin/seriallisten --config ${{ parameters.netlaunchConfigFile}}
 
       echo "Running script to stage and finalize A/B update..."
       ./bin/storm-trident helper ab-update \
@@ -135,6 +140,28 @@ steps:
     workingDirectory: $(Build.SourcesDirectory)
     displayName: "🔄 Stage and finalize A/B update into runtime OS B"
     condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
+
+  - bash: |
+      set -eux
+      if cat ${{ parameters.netlaunchConfigFile }} | grep -q "bmc:"; then
+        echo "Netlaunch config file contains 'bmc' keyword, retrieve serial output from seriallisten"
+        export SERIAL_LOG="${{ variables.TRIDENT_SOURCE_DIR }}/baremetal-serial.log"
+
+        # Output the serial log
+        if [ ! -f $SERIAL_LOG ]; then
+          echo "Serial log not found!"
+          echo "(No serial log captured)" > $SERIAL_LOG
+        fi
+      else
+        echo "Netlaunch config file does not contain 'bmc' keyword, retrieve serial output from local VM"
+        export SERIAL_LOG="$(find /tmp/*-serial0.log | head -n 1)"
+      fi
+
+      cp $SERIAL_LOG $(ob_outputDirectory)/serial-update-runtime-os-B.log
+      echo "Serial log found:"
+      cat $SERIAL_LOG
+    displayName: "Display serial output from update to B"
+    condition: and(always(), ne(variables['abActiveVolume'], 'null'))
 
   - template: ../testing_common/display-deployment-logs.yml
     parameters:
@@ -207,6 +234,8 @@ steps:
           -s "${{ parameters.artifactsDirectory }}" \
           -p ${{ parameters.netlistenPort }} > ./stage-finalize-ab-update-runtime-os-A.log 2>&1 &
 
+      ./bin/seriallisten --config ${{ parameters.netlaunchConfigFile}}
+
       echo "Running script to stage and finalize A/B update..."
       ./bin/storm-trident helper ab-update \
           "${{ parameters.sshKeyPath }}" \
@@ -228,6 +257,28 @@ steps:
     workingDirectory: $(Build.SourcesDirectory)
     displayName: "🔄 Stage and finalize A/B update into runtime OS A"
     condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
+
+  - bash: |
+      set -eux
+      if cat ${{ parameters.netlaunchConfigFile }} | grep -q "bmc:"; then
+        echo "Netlaunch config file contains 'bmc' keyword, retrieve serial output from seriallisten"
+        export SERIAL_LOG="${{ variables.TRIDENT_SOURCE_DIR }}/baremetal-serial.log"
+
+        # Output the serial log
+        if [ ! -f $SERIAL_LOG ]; then
+          echo "Serial log not found!"
+          echo "(No serial log captured)" > $SERIAL_LOG
+        fi
+      else
+        echo "Netlaunch config file does not contain 'bmc' keyword, retrieve serial output from local VM"
+        export SERIAL_LOG="$(find /tmp/*-serial0.log | head -n 1)"
+      fi
+
+      cp $SERIAL_LOG $(ob_outputDirectory)/serial-update-runtime-os-A.log
+      echo "Serial log found:"
+      cat $SERIAL_LOG
+    displayName: "Display serial output from update to A"
+    condition: and(always(), ne(variables['abActiveVolume'], 'null'))
 
   - template: ../testing_common/display-deployment-logs.yml
     parameters:
