not compile time

diff --git a/.pipelines/templates/stages/testing_common/e2e-test-run.yml b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
--- a/.pipelines/templates/stages/testing_common/e2e-test-run.yml
+++ b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
@@ -166,13 +166,14 @@ steps:
     displayName: "🅱️🔄 Stage and finalize A/B update into target OS B"
     condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
 
-  - ${{ if eq(parameters.tridentConfigurationName, 'auto-rollback') }}:
-      - bash: |
-          set -eu
-          # auto-rollback will fail the first update (to volume-b) and
-          # the rollback should boot to volume-a
-          echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
-        displayName: "Adjust active volume for auto-rollback scenario"
+  - bash: |
+      set -eu
+      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
+        # auto-rollback will fail the first update (to volume-b) and
+        # the rollback should boot to volume-a
+        echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
+      fi
+    displayName: "Adjust active volume for auto-rollback scenario"
 
   - template: ../testing_common/display-serial-logs.yml
     parameters:
@@ -239,13 +240,14 @@ steps:
       displayNameSpecifier: "A/B update into target OS B"
       artifactName: "junit_for_trident_ab_update_B"
 
-  - ${{ if eq(parameters.tridentConfigurationName, 'auto-rollback') }}:
-      - bash: |
-          set -eu
-          # for auto-rollback, only run the first update to test rollback
-          echo "##vso[task.setvariable variable=abActiveVolume]null"
-          echo "##vso[task.setvariable variable=skipJunitHandling]true"
-        displayName: "Limit subsequent testing for auto-rollback scenario"
+  - bash: |
+      set -eu
+      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
+        # for auto-rollback, only run the first update to test rollback
+        echo "##vso[task.setvariable variable=abActiveVolume]null"
+        echo "##vso[task.setvariable variable=skipJunitHandling]true"
+      fi
+    displayName: "Limit subsequent testing for auto-rollback scenario"
 
   - bash: |
       set -eux
