clean

diff --git a/.pipelines/templates/stages/testing_common/e2e-test-run.yml b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
--- a/.pipelines/templates/stages/testing_common/e2e-test-run.yml
+++ b/.pipelines/templates/stages/testing_common/e2e-test-run.yml
@@ -152,23 +152,27 @@ steps:
           --version $(version) \
           --stage-ab-update \
           --finalize-ab-update \
-          $PROXY_ARG $FORCED_ROLLBACK_ARG
+          $PROXY_ARG \
+          $FORCED_ROLLBACK_ARG
 
       current_version=$(echo $(version))
       new_version=$((current_version + 1))
       # Un-set the 'x' flag to avoid errors.
       set +x
       echo "##vso[task.setvariable variable=version]$new_version"
-      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
-        # auto-rollback should maintain active volume as volume-a
-        echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
-      else
-        echo "##vso[task.setvariable variable=abActiveVolume]volume-b"
-      fi
+      echo "##vso[task.setvariable variable=abActiveVolume]volume-b"
     timeoutInMinutes: 15
     workingDirectory: $(Build.SourcesDirectory)
     displayName: "🅱️🔄 Stage and finalize A/B update into target OS B"
     condition: and(succeeded(), ne(variables['abActiveVolume'], 'null'))
+
+  - ${{ if eq(parameters.tridentConfigurationName, 'auto-rollback') }}:
+      - bash: |
+          set -eu
+          # auto-rollback will fail the first update (to volume-b) and
+          # the rollback should boot to volume-a
+          echo "##vso[task.setvariable variable=abActiveVolume]volume-a"
+        displayName: "Adjust active volume for auto-rollback scenario"
 
   - template: ../testing_common/display-serial-logs.yml
     parameters:
@@ -235,15 +239,13 @@ steps:
       displayNameSpecifier: "A/B update into target OS B"
       artifactName: "junit_for_trident_ab_update_B"
 
-  - bash: |
-      set -eu
-      if [ ${{ parameters.tridentConfigurationName }} == 'auto-rollback' ]; then
-        # for auto-rollback, only run the first update to test rollback
-        echo "##vso[task.setvariable variable=abActiveVolume]null"
-        echo "##vso[task.setvariable variable=skipJunitHandling]true"
-      fi
-    workingDirectory: $(Build.SourcesDirectory)
-    displayName: "Limit subsequent testing for auto-rollback scenario"
+  - ${{ if eq(parameters.tridentConfigurationName, 'auto-rollback') }}:
+      - bash: |
+          set -eu
+          # for auto-rollback, only run the first update to test rollback
+          echo "##vso[task.setvariable variable=abActiveVolume]null"
+          echo "##vso[task.setvariable variable=skipJunitHandling]true"
+        displayName: "Limit subsequent testing for auto-rollback scenario"
 
   - bash: |
       set -eux
