Merged PR 20729: engineering: Add Trident rebuild -raid tests to baremetal pipeline runs
# 🔍 Description

What is this PR about? feature/doc/engineering/bug?
engineering: This PR focuses on simulating a disk failure on baremetal hardware  and test trident rebuild-raid.

# 🤔 Rationale

Why is this PR needed?
Cover more test cases for baremetal testing

# 📝 Checks

- [ ] Check [dev-docs/manual-validation.md](/dev-docs/manual-validation.md)

# 📌 Follow-ups

TODO:

- #0000

# 🗒️ Notes

test rebuild on baremetal

----
#### AI description  (iteration 1)
#### PR Classification
New feature

#### PR Summary
This pull request adds tests to simulate disk failure and trigger RAID rebuilds using Trident in baremetal pipeline runs.
- `.pipelines/templates/stages/testing_common/e2e-test-run.yml`: Added steps to clear the partition table of the `sdb` disk, reboot the host, check SSH connection post-reboot, and run a script to rebuild RAID arrays with Trident.

Related work items: #9474

diff --git a/.pipelines/templates/stages/testing_common/trident-rebuild.yml b/.pipelines/templates/stages/testing_common/trident-rebuild.yml
--- a/.pipelines/templates/stages/testing_common/trident-rebuild.yml
+++ b/.pipelines/templates/stages/testing_common/trident-rebuild.yml
@@ -24,6 +24,13 @@ parameters:
   - name: tridentConfigPath
     type: string 
 
+  - name: deploymentEnvironment  
+    type: string
+    default: virtualMachine
+    values:
+      - bareMetal
+      - virtualMachine
+
 steps:
 
   - bash: |
@@ -38,92 +45,108 @@ steps:
         fi
     displayName: "Check if Trident config requires rebuild-raid testing"
 
-  - bash: |
-      set -eux
-      echo "Efibootmgr entries in the VM."
-      ssh -o StrictHostKeyChecking=no -i ${{ parameters.sshKeyPath }} ${{ parameters.userName }}@${{ parameters.hostIp }} "sudo efibootmgr"
-      sudo virsh shutdown virtdeploy-vm-0
-      sudo rm -f /var/lib/libvirt/images/virtdeploy-pool/virtdeploy-vm-0-1-volume.qcow2
-      sudo qemu-img create -f qcow2 /var/lib/libvirt/images/virtdeploy-pool/virtdeploy-vm-0-1-volume.qcow2 16G
-    displayName: "Replace the test disk with a new disk"
-    condition: eq(variables['TEST_REBUILD_RAID'], 'True')
+  - ${{ if eq(parameters.deploymentEnvironment, 'bareMetal') }}:
+    - bash: |
+        set -eux
+        # clear the partition table of sdb disk
+        ssh -o StrictHostKeyChecking=no -i ${{ parameters.sshKeyPath }} ${{ parameters.userName }}@${{ parameters.hostIp }} "sudo dd if=/dev/zero of=/dev/sdb bs=512 count=1"
+        ssh -o StrictHostKeyChecking=no -i ${{ parameters.sshKeyPath }} ${{ parameters.userName }}@${{ parameters.hostIp }} "echo 'label: gpt' | sudo sfdisk /dev/sdb --force"
+        # Fail the RAID devices
+        python3 $(Build.SourcesDirectory)/e2e_tests/helpers/fail_raid_devices.py \
+            --ip-address ${{ parameters.hostIp }} \
+            --user-name ${{ parameters.userName }} \
+            --keys-file-path ${{ parameters.sshKeyPath }} 
+        ssh -o StrictHostKeyChecking=no -i ${{ parameters.sshKeyPath }} ${{ parameters.userName }}@${{ parameters.hostIp }} "sudo reboot" 
+      displayName: "Clear the partition table, fail RAID devices of sdb disk and reboot the host"
+      condition: and(succeeded(), eq(variables['TEST_REBUILD_RAID'], 'True')) 
 
-  - bash: |
-      set -eux
-      echo "Dump the VM before boot order change."
-      until sudo virsh dumpxml virtdeploy-vm-0; do 
-          sudo virsh list
-          sleep 0.1
-      done
-      echo "Changing the boot order of the VM to boot from sda."
-      python3 $(Build.SourcesDirectory)/.pipelines/templates/stages/testing_vm/update-vm-bootorder.py
-      echo "Dump the VM after boot order change."
-      until sudo virsh dumpxml virtdeploy-vm-0; do 
-          sudo virsh list
-          sleep 0.1
-      done
-    displayName: "Change boot order"
-    condition: eq(variables['TEST_REBUILD_RAID'], 'True')
+  - ${{ if eq(parameters.deploymentEnvironment, 'virtualMachine') }}:
+    - bash: |
+        set -eux
+        echo "Efibootmgr entries in the VM."
+        ssh -o StrictHostKeyChecking=no -i ${{ parameters.sshKeyPath }} ${{ parameters.userName }}@${{ parameters.hostIp }} "sudo efibootmgr"
+        sudo virsh shutdown virtdeploy-vm-0
+        sudo rm -f /var/lib/libvirt/images/virtdeploy-pool/virtdeploy-vm-0-1-volume.qcow2
+        sudo qemu-img create -f qcow2 /var/lib/libvirt/images/virtdeploy-pool/virtdeploy-vm-0-1-volume.qcow2 16G
+      displayName: "Replace the test disk with a new disk"
+      condition: and(succeeded(),eq(variables['TEST_REBUILD_RAID'], 'True')) 
 
-  - bash: |
-      set -eux
+    - bash: |
+        set -eux
+        echo "Dump the VM before boot order change."
+        until sudo virsh dumpxml virtdeploy-vm-0; do 
+            sudo virsh list
+            sleep 0.1
+        done
+        echo "Changing the boot order of the VM to boot from sda."
+        python3 $(Build.SourcesDirectory)/.pipelines/templates/stages/testing_vm/update-vm-bootorder.py
+        echo "Dump the VM after boot order change."
+        until sudo virsh dumpxml virtdeploy-vm-0; do 
+            sudo virsh list
+            sleep 0.1
+        done
+      displayName: "Change boot order"
+      condition: and(succeeded(),eq(variables['TEST_REBUILD_RAID'], 'True'))
 
-      # Name of the domain
-      DOMAIN_NAME="virtdeploy-vm-0"
+    - bash: |
+        set -eux
 
-      # Initial sleep time
-      sleep_time=10
+        # Name of the domain
+        DOMAIN_NAME="virtdeploy-vm-0"
 
-      # Check the state of the domain and run the loop
-      for (( i=1; i<=30; i++ )); do
-          domain_state=$(sudo virsh domstate $DOMAIN_NAME)
+        # Initial sleep time
+        sleep_time=10
 
-          if [[ $domain_state == "shut off" ]]; then
-              echo "The domain is shut off. Starting the domain..."
-              sudo virsh start $DOMAIN_NAME
-              echo "The domain has been started."
-              exit 0
-          else
-              echo "The domain is still running. Waiting for $sleep_time seconds..."
-              sleep $sleep_time
-              sleep_time=$((sleep_time + 10))
-          fi
-      done
+        # Check the state of the domain and run the loop
+        for (( i=1; i<=30; i++ )); do
+            domain_state=$(sudo virsh domstate $DOMAIN_NAME)
 
-      echo "The domain did not shut down after 30 attempts."
+            if [[ $domain_state == "shut off" ]]; then
+                echo "The domain is shut off. Starting the domain..."
+                sudo virsh start $DOMAIN_NAME
+                echo "The domain has been started."
+                exit 0
+            else
+                echo "The domain is still running. Waiting for $sleep_time seconds..."
+                sleep $sleep_time
+                sleep_time=$((sleep_time + 10))
+            fi
+        done
 
-    displayName: "Restart the VM"
-    condition: eq(variables['TEST_REBUILD_RAID'], 'True')
+        echo "The domain did not shut down after 30 attempts."
 
-  - bash: |
-      set -euxo pipefail
-      # Name of the domain
-      DOMAIN_NAME="virtdeploy-vm-0"
-      
-      # Get the VM serial log file path
-      VM_SERIAL_LOG=$(sudo virsh dumpxml $DOMAIN_NAME | grep -A 1 console | grep source | cut -d"'" -f2)
+      displayName: "Restart the VM"
+      condition: and(succeeded(),eq(variables['TEST_REBUILD_RAID'], 'True'))
 
-      # Wait until the serial log file is created
-      until [ -c "$VM_SERIAL_LOG" ]; do
-          sleep 0.1
-      done
+    - bash: |
+        set -euxo pipefail
+        # Name of the domain
+        DOMAIN_NAME="virtdeploy-vm-0"
+        
+        # Get the VM serial log file path
+        VM_SERIAL_LOG=$(sudo virsh dumpxml $DOMAIN_NAME | grep -A 1 console | grep source | cut -d"'" -f2)
 
-      echo "Found VM serial log file: $VM_SERIAL_LOG"
-      echo "VM serial log:"
+        # Wait until the serial log file is created
+        until [ -c "$VM_SERIAL_LOG" ]; do
+            sleep 0.1
+        done
 
-      # Execute wait_for_login.py to retrieve the serial log
-      sudo $(tridentSourceDirectory)/e2e_tests/helpers/wait_for_login.py \
-          -d "$VM_SERIAL_LOG" \
-          -o ./serial.log \
-          -t 500
+        echo "Found VM serial log file: $VM_SERIAL_LOG"
+        echo "VM serial log:"
 
-      # Capture the exit code from wait_for_login.py
-      WAIT_FOR_LOGIN_EXITCODE=$?
+        # Execute wait_for_login.py to retrieve the serial log
+        sudo $(tridentSourceDirectory)/e2e_tests/helpers/wait_for_login.py \
+            -d "$VM_SERIAL_LOG" \
+            -o ./serial.log \
+            -t 500
 
-      # Exit with the captured exit code
-      exit $WAIT_FOR_LOGIN_EXITCODE 
-    displayName: "Collect Serial Log of the VM"
-    condition: eq(variables['TEST_REBUILD_RAID'], 'True')  
+        # Capture the exit code from wait_for_login.py
+        WAIT_FOR_LOGIN_EXITCODE=$?
+
+        # Exit with the captured exit code
+        exit $WAIT_FOR_LOGIN_EXITCODE 
+      displayName: "Collect Serial Log of the VM"
+      condition: eq(variables['TEST_REBUILD_RAID'], 'True')  
 
   # TODO: Remove after trident-container-verity-testimage is being used for E2E tests (Task #9652). 
   - bash: |
@@ -143,7 +166,7 @@ steps:
           "${{ parameters.sshKeyPath }}" \
           "${{ parameters.userName }}" \
           "${{ parameters.hostIp }}"
-    displayName: "Check SSH connection after restarting the VM"
+    displayName: "Check SSH connection after restarting"
     condition: eq(variables['TEST_REBUILD_RAID'], 'True')
 
   - bash: |
