Merged PR 21073: engineering: Refactor Trident metrics template to prevent unnecessary execution and reuploads...
# 🔍 Description

What is this PR about? feature/doc/engineering/bug?

The use of a pipeline template call for metrics uploading is not ideal in our case because our e2e tests execute clean install and multiple A/B update tests, which need metrics processing and uploading each time. Templates cannot be called conditionally and therefore in our case, makes it harder to avoid executing the template when unecessary.

The metrics steps in our pipeline runs are being refactored to prevent unecessarry attempts to upload an empty file or even duplicate uploads when something like AB update steps get skipped. This PR addresses those issues by using metric file names are that are different for a step and can be verified before uploads. We also switch from using a template call to upload the metrics to our own upload script which does the necessary steps, and can be controlled better since its a bash step.

Also adds the trace file as a parameter to netlisten so that ab-update filenames can be different , to fix the issue of our metric steps reuploading the same clean install data in e2e tests where A/B updates get skipped.

# 🤔 Rationale

Why is this PR needed?

# 📝 Checks

- [ ] Check [dev-docs/manual-validation.md](/dev-docs/manual-validation.md)

# 📌 Follow-ups

TODO:

- #0000

# 🗒️ Notes

Refactor Trident metrics template to prevent wrongful execution and reuploads of same data files

----
#### AI description  (iteration 1)
#### PR Classification
Code cleanup and refactoring.

#### PR Summary
Refactored Trident metrics template to prevent wrongful execution and reuploads, and updated metrics file paths for better clarity.
- Refactored `/.pipelines/templates/stages/testing_common/trident-metrics.yml` to split steps into separate jobs for processing and uploading metrics.
- Updated metrics file paths in `/.pipelines/templates/stages/testing_baremetal/baremetal-testing.yml` to use more descriptive names.
- Changed metrics file paths in `/.pipelines/templates/stages/testing_common/e2e-ab-update-stage-finalize-test-run.yml` for better clarity.
- Modified metrics file paths in `/.pipelines/templates/stages/testing_common/e2e-test-run.yml` to use specific names for different stages.
- Updated `/.pipelines/templates/stages/testing_vm/netlaunch-testing.yml` to use a variable for the metrics file path.

Related work items: #9738

diff --git a/.pipelines/templates/stages/testing_common/trident-metrics.yml b/.pipelines/templates/stages/testing_common/trident-metrics.yml
--- a/.pipelines/templates/stages/testing_common/trident-metrics.yml
+++ b/.pipelines/templates/stages/testing_common/trident-metrics.yml
@@ -31,29 +31,37 @@ parameters:
 
 steps:
   - bash: |
-      set -eu
+      set -eux
+      # Check if the metrics file exists and is not empty
       if [ -s "${{ parameters.metricsFile }}" ]; then
-        echo "##vso[task.setvariable variable=ProcessMetricsFile]true"
+        set +x
+        echo "##vso[task.setvariable variable=UploadMetrics]True"
+        set -x
         echo "Metrics file exists and is not empty."
+
+        # Run the Python script to process the metrics
+        python3 ${{ parameters.tridentSourceDirectory }}/e2e_tests/helpers/process_trident_metrics.py \
+          --trident-config ${{ parameters.tridentConfigPath }}/trident-config.yaml \
+          --metrics-file ${{ parameters.metricsFile }}
+        
+        echo "Trident Metrics:"
+        cat ${{ parameters.metricsFile }}
       else
         if [[ "$AGENT_JOBSTATUS" == "Succeeded" ]]; then
-          echo "Metrics file does not exist or is empty, but there were no previous failures!"
-          echo "##vso[task.setvariable variable=ProcessMetricsFile]false"
-          echo "##vso[task.complete result=Failed;]"
+            echo "Metrics file does not exist or is empty, but there were no previous failures!"
+            set +x
+            echo "##vso[task.setvariable variable=UploadMetrics]False"
+            set -x
         else
           echo "Metrics file does not exist or is empty, but a previous failure occurred."
-          echo "##vso[task.setvariable variable=ProcessMetricsFile]false"
+          set +x
+          echo "##vso[task.setvariable variable=UploadMetrics]False"
+          set -x
         fi
       fi
-    displayName: "Check if metrics file exists and is not empty"
+    displayName: "Validate and Process Trident metrics file"
     condition: succeededOrFailed()
-
-  - bash: |
-      set -eux
-      python3 ${{ parameters.tridentSourceDirectory }}/e2e_tests/helpers/process_trident_metrics.py --trident-config ${{ parameters.tridentConfigPath }}/trident-config.yaml --metrics-file ${{ parameters.metricsFile }}
     workingDirectory: ${{ parameters.tridentSourceDirectory }}
-    displayName: "Process Trident metrics"
-    condition: eq(variables['ProcessMetricsFile'], 'true')
     env:
       TRIDENT_CONFIGURATION_NAME: ${{ parameters.tridentConfigurationName }}
       SOURCE_BRANCH_NAME: $(Build.SourceBranchName)
@@ -61,10 +69,36 @@ steps:
       RUNTIME_ENVIRONMENT: ${{ parameters.runtimeEnvironment }}
       PIPELINE_NAME: $(Build.DefinitionName)
 
-  - template: pipelines/templates/upload-metrics-step.yaml@platform-telemetry
-    parameters:
-      kustoDatabaseName: ${{ parameters.kustoDatabaseName }}
-      kustoTableName: ${{ parameters.kustoTableName }}
-      kustoTableMapping: ${{ parameters.kustoTableMapping }}
-      metricsFile: ${{ parameters.metricsFile }}
-      runOnFailure: true
+  - bash: |
+      set -ex
+      sudo apt update -y
+      sudo apt install -y python3 python3-pip azure-cli
+    displayName: "Install dependencies for metrics upload"
+    condition: and(succeeded(), eq(variables['UploadMetrics'], 'True'))
+    retryCountOnTaskFailure: 3
+
+  - task: AzureCLI@2.236.0
+    displayName: Azure CLI
+    inputs:
+      azureSubscription: bmp_perf_service_connection
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        set -e
+        az account show
+        azToken=$(az account get-access-token --resource "https://api.kusto.windows.net" | jq -r '.accessToken')
+        echo "##vso[task.setvariable variable=AZ_TOKEN]$azToken"
+    condition: and(succeeded(), eq(variables['UploadMetrics'], 'True'))
+    retryCountOnTaskFailure: 3
+
+  - checkout: platform-telemetry
+  - bash: |
+      chmod +x "$(Build.SourcesDirectory)/.pipelines/templates/stages/testing_common/scripts/upload_metrics.sh"
+      "$(Build.SourcesDirectory)/.pipelines/templates/stages/testing_common/scripts/upload_metrics.sh" \
+        "${{ parameters.metricsFile }}" \
+        "${{ parameters.kustoDatabaseName }}" \
+        "${{ parameters.kustoTableName }}" \
+        "${{ parameters.kustoTableMapping }}" \
+        "$(Pipeline.Workspace)/s/platform-telemetry"
+    displayName: "Upload metrics to Kusto"
+    condition: and(succeeded(), eq(variables['UploadMetrics'], 'True'))
