add extra output

diff --git a/.pipelines/templates/stages/testing_vm/netlaunch-testing.yml b/.pipelines/templates/stages/testing_vm/netlaunch-testing.yml
--- a/.pipelines/templates/stages/testing_vm/netlaunch-testing.yml
+++ b/.pipelines/templates/stages/testing_vm/netlaunch-testing.yml
@@ -200,7 +200,15 @@ stages:
               echo "Checking for SELinux violations with audit2allow"
               HOST_IP=$(jq -r '.virtualmachines[0].ip' $(argusToolkitSourceDirectory)/virt-deploy-metadata.json)
               ssh -o StrictHostKeyChecking=no -i $(tridentSourceDirectory)/e2e_tests/helpers/key testing-user@$HOST_IP \
-                'sudo audit2allow -i /var/log/audit/audit.log' || echo "audit2allow failed"
+                'sudo audit2allow -i /var/log/audit/audit.log' | { 
+                  output=$(cat)
+                  if [ -n "$output" ]; then
+                    echo "audit2allow output:"
+                    echo "$output"
+                  else
+                    echo "audit2allow had no output"
+                  fi
+                } || echo "audit2allow failed"
 
               echo "Looking for audit logs in VM"
               ssh -o StrictHostKeyChecking=no -i $(tridentSourceDirectory)/e2e_tests/helpers/key testing-user@$HOST_IP \
