Merged PR 18632: bug: wait fot ssh connection for 2 mins
sometimes trident0ci fails with  ssh -o StrictHostKeyChecking=no -i /mnt/vss/_work/1/s/e2e_tests/helpers/key testing-user@192.168.242.2 'sudo chown testing-user:testing-user /run && sudo chmod 755 /run'
ssh: connect to host 192.168.242.2 port 22: Connection refused

##[error]Bash exited with code '255'.

adding a wait time of 2 mins before scp

Related work items: #7411

diff --git a/.pipelines/templates/stages/deployment_testing/common_tasks/e2e-test-run.yml b/.pipelines/templates/stages/deployment_testing/common_tasks/e2e-test-run.yml
--- a/.pipelines/templates/stages/deployment_testing/common_tasks/e2e-test-run.yml
+++ b/.pipelines/templates/stages/deployment_testing/common_tasks/e2e-test-run.yml
@@ -31,10 +31,22 @@ steps:
  
   - bash: |
       set -eux
+      sshKeyPath="$(Build.SourcesDirectory)/e2e_tests/helpers/key"
+      # Check SSH connection and wait for 2 minutes if it fails
+      for i in {1..24}; do
+        ssh -q -o "StrictHostKeyChecking=no" -i "$sshKeyPath" testing-user@${{ parameters.hostIp }} exit
+        SSH_EXIT_CODE=$?
+        if [ $SSH_EXIT_CODE -eq 0 ]; then
+          echo "SSH connection successful. VM is up and running."
+            break
+        else
+            echo "SSH connection failed. Waiting for 5 seconds before retrying..."
+            sleep 5
+        fi
+      done
       ls -ltr $(System.ArtifactsDirectory)
       verityExists=$(sudo yq e '.hostConfiguration.storage.verity != null' "${{ parameters.tridentConfigPath }}/trident-config.yaml")
-      abupdateExists=$(sudo yq e '.hostConfiguration.storage.abUpdate != null' "${{ parameters.tridentConfigPath }}/trident-config.yaml")
-      sshKeyPath="$(Build.SourcesDirectory)/e2e_tests/helpers/key"
+      abupdateExists=$(sudo yq e '.hostConfiguration.storage.abUpdate != null' "${{ parameters.tridentConfigPath }}/trident-config.yaml") 
       if [ "$verityExists" == true ] && [ "$abupdateExists" == true ]; then
           artifactsDirectory="$(System.ArtifactsDirectory)/trident-verity-testimage"
           destinationDirectory="/run"
