Merged PR 20246: bug: Check if metrics file is not empty before continuing with processing and upload steps
# 🔍 Description

What is this PR about? feature/doc/engineering/bug?

Add a step added allows us to catch failure's if our metrics files aren't getting created when they should be existing.
Also removes the need to pass around `runOnFailure` in the pipeline files because we are controlling template calling if we have a metrics file to upload, and we will never want runOnFailure to be false.
This will still have the uploader fail when the file is empty, but with a fix that was merged for that repo, it now fails gracefully.

PR run with a failure + upload  example: https://dev.azure.com/mariner-org/ECF/_build/results?buildId=637149&view=logs&s=c27e0f8a-60ac-56ba-f786-e8b0d818e56a&j=052fed38-d3f6-5dba-e4ce-f274459d8b3b

PR run with missing file example: https://dev.azure.com/mariner-org/ECF/_build/results?buildId=637064&view=logs&j=052fed38-d3f6-5dba-e4ce-f274459d8b3b&t=cd90e22b-bee0-50d3-7bae-698481318e79

# 🤔 Rationale

Why is this PR needed?

Poor handling of ingestion script when file is empty or doesn't exist.

# 📝 Checks

- [ ] Check [dev-docs/manual-validation.md](/dev-docs/manual-validation.md)

# 📌 Follow-ups

TODO:

- #0000

# 🗒️ Notes

----
#### AI description  (iteration 1)
#### PR Classification
Bug fix to prevent processing and uploading metrics when the metrics file is missing or empty.

#### PR Summary
This pull request adds a condition to check if the metrics file exists and is not empty before proceeding with processing and uploading steps.
- `.pipelines/templates/stages/deployment_testing/common_tasks/trident-metrics.yml`: Added a check to verify the metrics file is not empty before processing and uploading.
- `.pipelines/templates/stages/deployment_testing/vm/netlaunch-testing.yml`: Temporarily changed the metrics file path for testing purposes.

Related work items: #8562

diff --git a/.pipelines/templates/stages/deployment_testing/common_tasks/trident-metrics.yml b/.pipelines/templates/stages/deployment_testing/common_tasks/trident-metrics.yml
--- a/.pipelines/templates/stages/deployment_testing/common_tasks/trident-metrics.yml
+++ b/.pipelines/templates/stages/deployment_testing/common_tasks/trident-metrics.yml
@@ -26,17 +26,31 @@ parameters:
     type: string
     default: "trident_mapping"
 
-  - name: runOnFailure
-    type: boolean
-    default: false
-
 steps:
+  - bash: |
+      set -eu
+      if [ -s "${{ parameters.metricsFile }}" ]; then
+        echo "##vso[task.setvariable variable=ProcessMetricsFile]true"
+        echo "Metrics file exists and is not empty."
+      else
+        if [[ "$AGENT_JOBSTATUS" == "Succeeded" ]]; then
+          echo "Metrics file does not exist or is empty, but there were no previous failures!"
+          echo "##vso[task.setvariable variable=ProcessMetricsFile]false"
+          echo "##vso[task.complete result=Failed;]"
+        else
+          echo "Metrics file does not exist or is empty, but a previous failure occurred."
+          echo "##vso[task.setvariable variable=ProcessMetricsFile]false"
+        fi
+      fi
+    displayName: "Check if metrics file exists and is not empty"
+    condition: succeededOrFailed()
+
   - bash: |
       set -eux
       python3 ${{ parameters.tridentSourceDirectory }}/e2e_tests/helpers/process_trident_metrics.py --trident-config ${{ parameters.tridentConfigPath }}/trident-config.yaml --metrics-file ${{ parameters.metricsFile }}
     workingDirectory: ${{ parameters.tridentSourceDirectory }}
     displayName: "Process Trident metrics"
-    condition: or(succeeded(), and(succeededOrFailed(), eq('${{ parameters.runOnFailure }}', true)))
+    condition: eq(variables['ProcessMetricsFile'], 'true')
     env:
       TRIDENT_CONFIGURATION_NAME: ${{ parameters.tridentConfigurationName }}
       SOURCE_BRANCH_NAME: $(Build.SourceBranchName)
@@ -49,4 +63,4 @@ steps:
       kustoTableName: ${{ parameters.kustoTableName }}
       kustoTableMapping: ${{ parameters.kustoTableMapping }}
       metricsFile: ${{ parameters.metricsFile }}
-      runOnFailure: ${{ parameters.runOnFailure }}
+      runOnFailure: true
